### ISSUE TITLE
Problema no endpoint Get .../rulesheets/{id}

### ISSUE THREAD

**Issue by vivaldomp** [bancodobrasil/featws-api#52]
Ao tentar consultar uma rulesheet por ID conforme endpoint da API GET /rulesheets/{id} os fields FEATURES e PARAMETERS não são retornados conforme figura abaixo:

![Screenshot from 2022-10-14 12-57-03](https://user-images.githubusercontent.com/10130162/195889945-51e821c4-a829-474f-a037-df0529d6627f.png)

**Comment by vivaldomp** [comment]
Outro erro está na recuperação de regras do tipo object. Na figura acima o retorno do campo APW_SIDEBAR_OPTIONS está truncado e não corresponde ao definido na base de conhecimentos https://canais.fontes.intranet.bb.com.br/cfe/cfe-featws-rules-dev-apw-teste/-/blob/master/rules.featws.

**Comment by aaugustogv** [comment]
Issue do Get realizada, estamos acompanhando a do Object em outra Issue.
